FROM nvidia/cuda:10.2-devel-ubuntu18.04

COPY docker/install_system.sh install_system.sh
RUN bash install_system.sh

COPY docker/install_python.sh install_python.sh
RUN bash install_python.sh gpu

ENV WORKDIR=/tp3d
WORKDIR $WORKDIR

COPY pyproject.toml pyproject.toml
COPY torch_points3d/__init__.py torch_points3d/__init__.py
COPY README.md README.md

RUN FORCE_CUDA=1 TORCH_CUDA_ARCH_LIST="3.5 5.2 6.0 6.1 7.0+PTX" pip3 install . && rm -rf /root/.cache

COPY . .
