# Those arguments defines the training hyper-parameters
training:
    shuffle: True
    num_workers: 6
    batch_size: 16
    cuda: 1
    precompute_multi_scale: False # Compute multiscate features on cpu for faster training / inference
    epochs: 100
    grad_clip: -1
    optimizer:
        class: Adam
        params:
            lr: 0.001
    learning_rate:
        scheduler_type: "step_decay"
        base_lr: ${optimizer.params.lr}
        lr_decay: 0.5
        decay_step: 200000
        lr_clip: 1e-5
    weight_name: "latest" # Used during resume, select with model to load from [miou, macc, acc..., latest]
    enable_cudnn: True
    checkpoint_dir: ""
    resume: True

# Those arguments within experiment defines which model, dataset and task to be created for benchmarking
# parameters for Weights and Biases
wandb:
    project: default
    log: False

    # parameters for TensorBoard Visualization
tensorboard:
    log: True
