# @package _group_
activate: False
format: ["ply", "tensorboard"]
num_samples_per_epoch: 10
deterministic: True # False -> Randomly sample elements from epoch to epoch
saved_keys:
  pos: [['x', 'float'], ['y', 'float'], ['z', 'float']]
  y: [['l', 'float']]
  pred: [['p', 'float']]
ply_format: 'binary_big_endian'
tensorboard_mesh:
  label: 'y'
  prediction: 'pred'
