visualization:
  activate: True
  format: "pointcloud" # image will come later
  num_samples_per_epoch: 3
  deterministic: False # False -> Randomly sample elements from epoch to epoch
  saved_keys: 
    pos: [['x', 'float'], ['y', 'float'], ['z', 'float']]
    y: [['l', 'int']]
    pred: [['p', 'int']]