num_workers: 2
batch_size: 16
cuda: 0
weight_name: "miou" # Used during resume, select with model to load from [miou, macc, acc..., latest]
enable_cudnn: True
checkpoint_dir: "/home/nicolas/deeppointcloud-benchmarks/outputs/2020-02-24/15-02-47" # "{your_path}/outputs/2020-01-28/11-04-13" for example
model_name: pointnet2_charlesssg
enable_dropout: False
forward_category: "Cap" #Category of the data in the folder to be infered
output_path: "/home/nicolas/deeppointcloud-benchmarks/forward_scripts/out" # Where the output goes
dataroot: "/home/nicolas/deeppointcloud-benchmarks/forward_scripts/test_data" # Folder where to find the data