name: pypi_publish

on:
    push:
      tags:
      - 'v*'

jobs:
    pypi:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Python 3.6
          uses: actions/setup-python@v1
          with:
            python-version: 3.6

        - name: Install poetry
          run: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python

        - name: Display Tag
          id: tag
          run: |
              echo "Current tag : ${{ github.ref }}"

        - name: Build project for distribution
          if: startsWith(github.ref, 'refs/tags/v')
          run: |
              $HOME/.poetry/bin/poetry build

        - name: Publish to PyPI
          if: startsWith(github.ref, 'refs/tags/v')
          env:
              POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
          run: |
              $HOME/.poetry/bin/poetry publish
